#! /bin/sh

# ██████╗ ███████╗██████╗ ██╗    ██╗███╗   ███╗
# ██╔══██╗██╔════╝██╔══██╗██║    ██║████╗ ████║
# ██████╔╝███████╗██████╔╝██║ █╗ ██║██╔████╔██║
# ██╔══██╗╚════██║██╔═══╝ ██║███╗██║██║╚██╔╝██║
# ██████╔╝███████║██║     ╚███╔███╔╝██║ ╚═╝ ██║
# ╚═════╝ ╚══════╝╚═╝      ╚══╝╚══╝ ╚═╝     ╚═╝
# Desktop Config                                              

##### AUTOSTART ################################################################

pgrep -x sxhkd > /dev/null || sxhkd &
bspc rule -r "*"
nitrogen --restore &
nm-applet &
$HOME/scripts/setup_xrandr.sh
$HOME/.config/polybar/launch.sh

##### BSPWM CONFIG #############################################################

bspc monitor DP-2   -d 1 2 3 4 5
bspc monitor HDMI-0 -d 6 7 8 9 10

bspc config border_width         2
bspc config window_gap           0

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color		"#444444"
bspc config active_border_color		"#444444"
bspc config focused_border_color	"#D03408"
bspc config presel_feedback_color	"#FC642C"

##### RULES ####################################################################

#bspc rule -a firefox desktop='^1' follow=on
#bpsc rule -a thunderbird state=fullscreen
bspc rule -a discord desktop='^9'
bspc rule -a Spotify state=fullscreen
