require('plugins')
require('lsp-config')
require('settings')
require('keymaps')

require('plug-config.treesitter')
require('plug-config.nvimtree')
require('plug-config.lualine')
require('plug-config.cmp')
require('plug-config.autopairs')
require('plug-config.toggleterm')
