######################
#  Internal Modules  #
######################

[module/i3]
type = internal/i3
format = <label-state> <label-mode>
index-sort = true
wrapping-scroll = false
pin-workspaces = true

label-mode-padding = 2
label-mode-foreground = #000
label-mode-background = ${colors.primary}

; focused = Active workspace on focused monitor
label-focused = %index%
label-focused-background = ${colors.background-alt}
label-focused-underline= ${colors.primary}
label-focused-padding = 2

; unfocused = Inactive workspace on any monitor
label-unfocused = %index%
label-unfocused-padding = 2

; visible = Active workspace on unfocused monitor
label-visible = %index%
label-visible-background = ${self.label-focused-background}
label-visible-underline = ${self.label-focused-underline}
label-visible-padding = ${self.label-focused-padding}

; urgent = Workspace with urgency hint set
label-urgent = %index%
label-urgent-background = ${colors.alert}
label-urgent-padding = 2


[module/pulseaudio]
type = internal/pulseaudio

format-volume = <label-volume> 
label-volume =  %percentage%%
label-volume-foreground = ${colors.foreground}

label-muted =  muted
label-muted-foreground = #666


[module/date]
type = internal/date
interval = 1.0

date = [%A] %d %B
date-alt = " %A, %d %B %Y"

time = %I:%M %p
time-alt = %k:%M:%S

format-prefix = " "
format-prefix-foreground = ${colors.foreground-alt}
format-underline = ${colors.secondary}

label = %date% - %time%


[module/cpu]
type = internal/cpu
interval = 2
format-prefix = ""
format-prefix-foreground = ${colors.foreground}
label = %percentage:2%%


[module/memory]
type = internal/memory
interval = 2
format-prefix = "﬙ "
format-prefix-foreground = ${colors.foreground}
label = %percentage_used%%


[module/temperature]
type = internal/temperature
thermal-zone = 0
warn-temperature = 70

format = <ramp> <label>
format-warn = <ramp> <label-warn>

label = %temperature-c%
label-warn = %temperature-c%
label-warn-foreground = ${colors.alert}

ramp-0 = 
ramp-1 = 
ramp-2 = 
ramp-foreground = ${colors.foreground}


[module/keyboard]
type = internal/xkeyboard
blacklist-0 = num lock

format = <label-indicator>
format-font = 2
format-prefix = " "
format-prefix-foreground = ${colors.primary}
format-foreground = ${colors.secondary}

label-indicator-on = %icon%
label-indicator-off = %icon%
label-indicator-on-capslock = ""
label-indicator-off-capslock = ""


####################
#  Custom Modules  #
####################

[module/sep]
type = custom/text
content = "|"
content-foreground = ${colors.separator}
content-font = 2


[module/distro]
type = custom/text
content = 
content-foreground = ${colors.primary}
content-font = 2
