[module/sep]
type = custom/text
content = "|"
content-foreground = ${colors.separator}
content-font = 2

[module/distro]
type = custom/text
content = 
content-foreground = ${colors.primary}
content-font = 2

[module/bspwm]
type = internal/bspwm

label-active-font = 1

ws-icon-0 = 1;
ws-icon-1 = 2;
ws-icon-2 = 3;
ws-icon-3 = 8;
ws-icon-4 = 9;ﭮ
ws-icon-5 = 10;
ws-icon-default = π

label-focused = %icon%
label-focused-foreground = ${colors.primary}
label-focused-background = ${colors.background}
;label-focused-underline = ${colors.primary}
label-focused-padding = 1
label-focused-font = 2

label-occupied = %icon%
label-occupied-foreground = ${colors.foreground}
label-occupied-padding = 1
label-occupied-font = 2

label-urgent = %index%!
label-urgent-background = ${colors.alert}
label-urgent-padding = 1
label-urgent-font = 2

label-empty = %icon%
label-empty-foreground = ${colors.inactive}
label-empty-padding = 1
label-empty-font = 2

; Separator in between workspaces
; label-separator = |

[module/date]
type = internal/date
interval = 1.0

date = [%A] %d %B
date-alt = " %A, %d %B %Y"

time = %I:%M %p
time-alt = %k:%M:%S

format-prefix = " "
format-prefix-foreground = ${colors.foreground-alt}
format-underline = ${colors.secondary}

label = %date% - %time%

[module/wlan]
type = internal/network
interface = wlp6s0
interval = 3.0

;format-connected = <ramp-signal> <label-connected>
format-connected =  <label-connected>
format-connected-underline = ${colors.secondary}
label-connected = %essid%

format-disconnected =
;format-disconnected = <label-disconnected>
;format-disconnected-underline = ${self.format-connected-underline}
;label-disconnected = %ifname% disconnected
;label-disconnected-foreground = ${colors.foreground-alt}

;ramp-signal-0 = 
;ramp-signal-1 = 
;ramp-signal-2 = 
;ramp-signal-foreground = ${colors.foreground-alt}

[module/battery]
type = internal/battery
battery = BAT1
adapter = AC
full-at = 99

format-charging = <animation-charging> <label-charging>
format-discharging = <ramp-capacity> <label-discharging>
format-full-prefix = " "
format-full-prefix-foreground = ${colors.foreground}
;format-full-underline = ${colors.primary}

ramp-capacity-0 = 
ramp-capacity-1 = 
ramp-capacity-2 = 
ramp-capacity-3 = 
ramp-capacity-4 = 
ramp-capacity-foreground = ${colors.foreground}

animation-charging-0 = 
animation-charging-1 = 
animation-charging-2 = 
animation-charging-foreground = ${colors.foreground}
animation-charging-framerate = 750

[module/cpu]
type = internal/cpu
interval = 2
format-prefix = ""
format-prefix-foreground = ${colors.foreground}
label = %percentage:2%%

[module/memory]
type = internal/memory
interval = 2
format-prefix = "﬙ "
format-prefix-foreground = ${colors.foreground}
label = %percentage_used%%

[module/temperature]
type = internal/temperature
thermal-zone = 0
warn-temperature = 70

format = <ramp> <label>
format-warn = <ramp> <label-warn>

label = %temperature-c%
label-warn = %temperature-c%
label-warn-foreground = ${colors.alert}

ramp-0 = 
ramp-1 = 
ramp-2 = 
ramp-foreground = ${colors.foreground}

[module/pulseaudio]
type = internal/pulseaudio

format-volume = <label-volume> 
label-volume =  %percentage%%
label-volume-foreground = ${colors.foreground}

label-muted =  muted
label-muted-foreground = #666

[module/updates]
type = custom/script

exec = ~/.config/polybar/scripts/updates.sh

tail = true

format =  <label> updates
format-background = ${colors.backgrond}
format-foreground = ${colors.primary}
format-padding = 1

[module/keyboard]
type = internal/xkeyboard
blacklist-0 = num lock

format = <label-indicator>
format-font = 2
format-prefix = " "
format-prefix-foreground = ${colors.primary}
format-foreground = ${colors.secondary}

label-indicator-on = %icon%
label-indicator-off = %icon%
label-indicator-on-capslock = ""
label-indicator-off-capslock = ""
