# __          __        _                                  
# \ \        / /       | |                                 
#  \ \  /\  / /__  _ __| | _____ _ __   __ _  ___ ___  ___ 
#   \ \/  \/ / _ \| '__| |/ / __| '_ \ / _` |/ __/ _ \/ __|
#    \  /\  / (_) | |  |   <\__ \ |_) | (_| | (_|  __/\__ \
#     \/  \/ \___/|_|  |_|\_\___/ .__/ \__,_|\___\___||___/
#                               | |                        
#                               |_|                        

##### Workspaces ###################################################################################
# Assign workspaces to specific monitors
# Primary monitor
workspace 1 output DP-2
workspace 2 output DP-2
workspace 3 output DP-2
workspace 4 output DP-2
workspace 5 output DP-2

# Secondary monitor
workspace 6 output HDMI-0
workspace 7 output HDMI-0
workspace 8 output HDMI-0
workspace 9 output HDMI-0
workspace 10 output HDMI-0

##### Windows ######################################################################################
# Floating windows
for_window [window_role="pop-up"]       floating enable
for_window [window_role="task_dialog"]  floating enable

# Steam
for_window [title="^Friends List$"]     floating enable
for_window [title="^Steam - News "]     floating enable

# Virt-Manager
for_window [class="Virt-manager"]       floating enable

# Assign windows to specific workspaces
assign [class="discord"] 9
for_window [class="Spotify"] move container to workspace 10

# Mouse options
focus_follows_mouse yes

