# ██╗  ██╗██╗████████╗████████╗██╗   ██╗
# ██║ ██╔╝██║╚══██╔══╝╚══██╔══╝╚██╗ ██╔╝
# █████╔╝ ██║   ██║      ██║    ╚████╔╝ 
# ██╔═██╗ ██║   ██║      ██║     ╚██╔╝  
# ██║  ██╗██║   ██║      ██║      ██║   
# ╚═╝  ╚═╝╚═╝   ╚═╝      ╚═╝      ╚═╝   
# Shared Config
                                      
# vim:fileencoding=utf-8:ft=conf:foldmethod=marker

##### FONTS ####################################################################

font_family	 JetBrainsMono
bold_font	 auto
italic_font	 auto
bold_italic_font auto
font_size	 14

##### MOUSE ####################################################################

mouse_hide_wait 	-1
focus_follows_mouse 	no

##### URLS #####################################################################

copy_on_select yes

##### WINDOW ###################################################################
#window_padding_width 5
#background_opacity 0.85

##### COLORS ###################################################################
include colors.conf
